# Generated by Django 5.2.1 on 2025-06-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='amount',
            field=models.FloatField(help_text='In dollars (e.g., 9.99)'),
        ),
    ]
