# Generated by Django 5.2.1 on 2025-06-10 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=255)),
                ('menu_type', models.CharField(help_text='Comma-separated menu types (e.g. breakfast, lunch, dinner)', max_length=255)),
                ('tags', models.CharField(help_text='Comma-separated tags (e.g. vegan, spicy, gluten-free)', max_length=255)),
                ('dish_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_percent_markup', models.DecimalField(decimal_places=2, help_text='e.g., 25.00 for 25% markup', max_digits=5)),
                ('date_to_serve', models.DateField()),
                ('cooking_station', models.CharField(max_length=255)),
                ('text_instructions', models.TextField()),
                ('dish_description', models.TextField()),
                ('ingredients', models.TextField(help_text='List of ingredients (comma or line separated)')),
                ('directions', models.TextField(help_text='Step-by-step cooking directions')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
