# Generated by Django 5.2.1 on 2025-06-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManualRecipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualrecipe',
            name='cooking_station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manualrecipe',
            name='date_to_serve',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualrecipe',
            name='dish_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='manualrecipe',
            name='food_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='manualrecipe',
            name='food_percent_markup',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g., 25.00 for 25% markup', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='manualrecipe',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g. vegan, spicy, gluten-free)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manualrecipe',
            name='text_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
