# Generated by Django 5.2.1 on 2025-06-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManualRecipe', '0002_alter_manualrecipe_cooking_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualrecipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/recipes_images/'),
        ),
    ]
