# Generated by Django 5.2.1 on 2025-08-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManualRecipe', '0003_alter_manualrecipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualrecipe',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
