# Generated by Django 5.2.1 on 2025-06-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AiRecipe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeStep',
        ),
    ]
