# Generated by Django 5.2.1 on 2025-06-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiRecipe', '0002_delete_recipestep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigeneratedrecipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aigeneratedrecipe',
            name='title',
        ),
        migrations.AddField(
            model_name='aigeneratedrecipe',
            name='cuisine',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
