# Generated by Django 5.2.1 on 2025-06-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiRecipe', '0003_remove_aigeneratedrecipe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigeneratedrecipe',
            name='cuisine',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
