# Generated by Django 5.2.1 on 2025-07-27 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiRecipe', '0004_alter_aigeneratedrecipe_cuisine'),
        ('ManualRecipe', '0003_alter_manualrecipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.TextField(help_text='AI-generated pro tips for the recipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manual_recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_tips', to='ManualRecipe.manualrecipe')),
            ],
        ),
    ]
