# Generated by Django 5.2.1 on 2025-08-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiRecipe', '0005_protips'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedrecipe',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
