# Generated by Django 5.2.1 on 2025-08-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiRecipe', '0006_aigeneratedrecipe_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigeneratedrecipe',
            name='image_url',
            field=models.URLField(max_length=1024),
        ),
    ]
