# Generated by Django 5.2.1 on 2025-08-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiRecipe', '0007_alter_aigeneratedrecipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedrecipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
    ]
