# Generated by Django 5.2.1 on 2025-08-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiRecipe', '0008_aigeneratedrecipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigeneratedrecipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/ai/recipes/images/'),
        ),
        migrations.AlterField(
            model_name='aigeneratedrecipe',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
